### PR TITLE
Upgraded jenkins to include docker, updated readme

### PR DESCRIPTION
**Pull request by artem-IST**
# What's New
-   Upgraded the Jenkins image to have docker installed.
-   Updated the README
-   Created a two new _docker-compose_, one for local dev/testing and another for the standard IST dockerhub image
# Testing
- Run it!

### CODE REVIEW

**Comment by madisonb** [comment]
what is this actually doing? allowing docker to be ran on the cli within the jenkins container? Why not use something like https://wiki.jenkins-ci.org/display/JENKINS/Docker+build+step+plugin to ensure you can run docker commands within Jenkins?

**Comment by artem-IST** [comment]
Yes, it allows for docker to run inside of Jenkins. That plugin alone is worthless without docker actually being installed

**Comment by madisonb** [comment]
I also dont understand the use case of docker compose here when we only have 1 image. This also isnt compatible with the shell scripts to stop/start/refresh our running jenkins docker image that is not contained within this repo.

**Comment by artem-IST** [comment]
The use case is that it doesn't require you to manually type in that long docker command in order to get the container to run.

About the shell scripts, you can just change the container name to whatever you want in the docker-compose file so that it matches the scripts on the host machine

**Comment by artem-IST** [comment]
I updated the readme and the compose file. 

The whole purpose of the compose file is to basically allow for your local machine to run the container without needing to type in that long command manually. It also allows you to build the container without manually providing a tag to the `docker build` command. Does that make sense? It is not supposed to interfere with anything that we have outside of this repo. Whatever jenkins scripts we have on our servers can stay as is. 

Additionally, It also references the image that is currently sitting in dockerhub, which was not the case before, as the image name to start the container was `ist/jenkins[version]` instead of `istresearch/jenkins:latest`

Finally, as I mentioned before, all of the docker plugins on jenkins are worthless without docker actually being installed on the container, hence why this pull request exists.

@madisonb

**Pull request merged**
